export const sliderItems = [
  {
    id: 1,
    img: "https://i.ibb.co/jyPc75L/celana-jeans.png",
    title: "Jeans Gaul",
    desc: "Kualitas Tak Terbatas.",
    bg: "f5fafd",
  },
  {
    id: 2,
    img: "https://i.ibb.co/Wsj9GLS/hoodie-putih.png",
    title: "Hoodie KW",
    desc: "Dapatkan Diskon 50.5%",
    bg: "fcf1ed",
  },
  {
    id: 3,
    img: "https://i.ibb.co/djNb12m/kaos-jean.png",
    title: "Kaos Anti Air",
    desc: "Jangan Dibeli Gak Bisa Dicuci",
    bg: "fbf0f4",
  },
];

export const categories = [
  {
    id: 1,
    title: "man",
  },
  {
    id: 2,
    title: "bag",
  },
  {
    id: 3,
    title: "shirt",
  },
  {
    id: 4,
    title: "jacket",
  },
  {
    id: 5,
    title: "sweater",
  },
  {
    id: 6,
    title: "boxer",
  },
  {
    id: 7,
    title: "hat",
  },
];

export const productPromo = [
  {
    id: 1,
    img: "https://i.ibb.co/jyPc75L/celana-jeans.png",
    title: "Celana Jeans",
    discount: "Diskon s/d 35%",
    kategory: "Celana",
  },
  {
    id: 2,
    img: "https://i.ibb.co/djNb12m/kaos-jean.png",
    title: "Kaos Polos",
    discount: "Diskon s/d 45%",
    kategory: "Kaos",
  },
  {
    id: 3,
    img: "https://i.ibb.co/GsCM7sM/kaos-polos.png",
    title: "Baju Musiman",
    discount: "Diskon s/d 20%",
    kategory: "Baju",
  },
  {
    id: 4,
    img: "https://i.ibb.co/hDDR2zG/jaket-jeans.png",
    title: "Jacket",
    discount: "Diskon s/d 35%",
    kategory: "Jacket Jeans",
  },
  {
    id: 5,
    img: "https://i.ibb.co/1XbfbnK/celana-jeans-pendek.png",
    title: "Celana Jeans",
    discount: "Diskon s/d 55%",
    kategory: "Celana",
  },
  {
    id: 6,
    img: "https://i.ibb.co/F3BW5c0/sepatu-nike-winflo.png",
    title: "Nike-Winflow",
    discount: "Diskon s/d 80%",
    kategory: "Sepatu",
  },
  {
    id: 7,
    img: "https://i.ibb.co/nw4PK5B/sepatu-nike.png",
    title: "Sepatu Nike",
    discount: "Diskon s/d 80%",
    kategory: "Sepatu",
  },
  {
    id: 8,
    img: "https://i.ibb.co/Wsj9GLS/hoodie-putih.png",
    title: "Hoodie",
    discount: "Diskon s/d 80%",
    kategory: "Hoodie",
  },
];

export const product = [
  {
    id: 1,
    img: "https://i.ibb.co/jyPc75L/celana-jeans.png",
    title: "Celana Jeans",
    harga: "Rp75.000,00",
    kategory: "Celana",
  },
  {
    id: 2,
    img: "https://i.ibb.co/djNb12m/kaos-jean.png",
    title: "Kaos Polos",
    harga: "Rp65.000,00",
    kategory: "Kaos",
  },
  {
    id: 3,
    img: "https://i.ibb.co/GsCM7sM/kaos-polos.png",
    title: "Baju Musiman",
    harga: "Rp40.000,00",
    kategory: "Baju",
  },
  {
    id: 4,
    img: "https://i.ibb.co/hDDR2zG/jaket-jeans.png",
    title: "Jacket",
    harga: "Rp95.000,00",
    kategory: "Jacket Jeans",
  },
  {
    id: 5,
    img: "https://i.ibb.co/1XbfbnK/celana-jeans-pendek.png",
    title: "Celana Jeans",
    harga: "Rp55.000,00",
    kategory: "Celana",
  },
  {
    id: 6,
    img: "https://i.ibb.co/F3BW5c0/sepatu-nike-winflo.png",
    title: "Nike-Winflow",
    harga: "Rp225.000,00",
    kategory: "Sepatu",
  },
  {
    id: 7,
    img: "https://i.ibb.co/nw4PK5B/sepatu-nike.png",
    title: "Sepatu Nike",
    harga: "Rp125.000,00",
    kategory: "Sepatu",
  },
  {
    id: 8,
    img: "https://i.ibb.co/Wsj9GLS/hoodie-putih.png",
    title: "Hoodie",
    harga: "Rp95.000,00",
    kategory: "Hoodie",
  },
];
export const productToDb = [
  {
    id: 1,
    img: "https://i.ibb.co/jyPc75L/celana-jeans.png",
    title: "Celana Jeans",
    harga: 75000,
    kategory: ["Celana"],
    size: ["M", "L", "Xl"],
    color: ["red", "blue", "black"],
    desc: "lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem,deleniti, ut facilis quibusdam laboriosam illum maxime ratione quassimilique quaerat iste ab provident earum eveniet.",
  },
  {
    id: 2,
    img: "https://i.ibb.co/djNb12m/kaos-jean.png",
    title: "Kaos Polos",
    harga: 60000,
    kategory: ["Kaos"],
    color: ["red", "blue", "black"],
    size: ["M", "L", "Xl"],
    desc: "lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem,deleniti, ut facilis quibusdam laboriosam illum maxime ratione quassimilique quaerat iste ab provident earum eveniet.",
  },
  {
    id: 3,
    img: "https://i.ibb.co/GsCM7sM/kaos-polos.png",
    title: "Baju Musiman",
    harga: 40000,
    kategory: ["Baju"],
    color: ["red", "blue", "black"],
    size: ["M", "L", "Xl"],
    desc: "lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem,deleniti, ut facilis quibusdam laboriosam illum maxime ratione quassimilique quaerat iste ab provident earum eveniet.",
  },
  {
    id: 4,
    img: "https://i.ibb.co/hDDR2zG/jaket-jeans.png",
    title: "Jacket",
    harga: 95000,
    kategory: ["Jacket Jeans"],
    color: ["red", "blue", "black"],
    size: ["M", "L", "Xl"],
    desc: "lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem,deleniti, ut facilis quibusdam laboriosam illum maxime ratione quassimilique quaerat iste ab provident earum eveniet.",
  },
  {
    id: 5,
    img: "https://i.ibb.co/1XbfbnK/celana-jeans-pendek.png",
    title: "Celana Jeans",
    harga: 55000,
    kategory: ["Celana"],
    color: ["red", "blue", "black"],
    size: ["M", "L", "Xl"],
    desc: "lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem,deleniti, ut facilis quibusdam laboriosam illum maxime ratione quassimilique quaerat iste ab provident earum eveniet.",
  },
  {
    id: 6,
    img: "https://i.ibb.co/F3BW5c0/sepatu-nike-winflo.png",
    title: "Nike-Winflow",
    harga: 225000,
    kategory: ["Sepatu"],
    color: ["red", "blue", "black"],
    size: ["M", "L", "Xl"],
    desc: "lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem,deleniti, ut facilis quibusdam laboriosam illum maxime ratione quassimilique quaerat iste ab provident earum eveniet.",
  },
  {
    id: 7,
    img: "https://i.ibb.co/nw4PK5B/sepatu-nike.png",
    title: "Sepatu Nike",
    harga: 125000,
    kategory: ["Sepatu"],
    color: ["red", "blue", "black"],
    size: ["M", "L", "Xl"],
    desc: "lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem,deleniti, ut facilis quibusdam laboriosam illum maxime ratione quassimilique quaerat iste ab provident earum eveniet.",
  },
  {
    id: 8,
    img: "https://i.ibb.co/Wsj9GLS/hoodie-putih.png",
    title: "Hoodie",
    harga: 95000,
    kategory: ["Hoodie"],
    color: ["red", "blue", "black"],
    size: ["M", "L", "Xl"],
    desc: "lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem,deleniti, ut facilis quibusdam laboriosam illum maxime ratione quassimilique quaerat iste ab provident earum eveniet.",
  },
];
